# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988cf499aba6b34e4917946053755d1e361e33ac23787c7630de694bd6e790ff8b2772b3f74f658c6c7eec53dd03e6694d9024874591bb2adfc9db73962170b5

test:
  secret_key_base: 826e92a041342e926285bbe55af2af251c2159e636699e8be72495073f4443afd77a12021cb3286140e87dd75ac7d09daa5906a8653c4df6c0c0f72e0af2e208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
